listen_addresses = '*'
hba_file = '/etc/postgresql/pg_hba.conf'
wal_level = replica
max_wal_senders = 5
wal_keep_size = 64
hot_standby = on
synchronous_commit = on
max_connections = 200
shared_buffers = 256MB
effective_cache_size = 512MB
log_min_duration_statement = 500
